Devel: Add support for dial-out, but fails...
Single call was feed to number, but smsgw fails, after that it fails
without calling.

Maybe to weak powersupply (since modem needs reinitialized).

Error message:

Message from SmsGW Daemon: dial_via_gsmmodem() failed with error:
Traceback (most recent call last):
  File "/usr/src/app/smsgwd", line 319, in make_call_for_all_backend_types
    [code, msg] = dial_via_gsmmodem(gsmmodems[gw], p['call'], p['msg'])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/smsgwd", line 189, in dial_via_gsmmodem
    call = gsmmodem.dial(to)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gsmmodem/modem.py", line 1062, in dial
    raise TimeoutException()
gsmmodem.exceptions.TimeoutException: None
Retry to connect to modem and resent...
Tried to reconnect and re- dial_via_gsmmodem() failed with error:
Traceback (most recent call last):
  File "/usr/src/app/smsgwd", line 319, in make_call_for_all_backend_types
    [code, msg] = dial_via_gsmmodem(gsmmodems[gw], p['call'], p['msg'])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/smsgwd", line 189, in dial_via_gsmmodem
    call = gsmmodem.dial(to)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gsmmodem/modem.py", line 1062, in dial
    raise TimeoutException()
gsmmodem.exceptions.TimeoutException: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/smsgwd", line 325, in make_call_for_all_backend_types
    gsmmodems[gw] = connect_to_gsmmodem(gw_params['tty'], gw_params['baud'], gw_params['pin'])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/smsgwd", line 128, in connect_to_gsmmodem
    modem.connect(
  File "/usr/local/lib/python3.11/site-packages/gsmmodem/modem.py", line 204, in connect
    self.write('AT', waitForResponse=True, timeout=0.5)
  File "/usr/local/lib/python3.11/site-packages/gsmmodem/modem.py", line 464, in write
    responseLines = super(GsmModem, self).write(data + writeTerm, waitForResponse=waitForResponse, timeout=timeout, expectedResponseTermSeq=expectedResponseTermSeq)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gsmmodem/serial_comms.py", line 132, in write
    self.serial.write(data)
  File "/usr/local/lib/python3.11/site-packages/serial/serialposix.py", line 615, in write
    raise PortNotOpenError()
serial.serialutil.PortNotOpenError: Attempting to use a port that is not open